name: flutter_app
description: "Preloved Closet Manager Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0

  # State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.5

  # Network and API
  http: ^1.2.1
  dio: ^5.4.3
  connectivity_plus: ^5.0.2

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Authentication
  jwt_decoder: ^2.0.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4

  # Forms and Validation
  form_field_validator: ^1.1.0
  image_picker: ^1.0.7
  image_cropper: ^9.1.0
  
  # ReCAPTCHA
  g_recaptcha_v3: ^0.0.5

  # Navigation
  go_router: ^14.1.2
  
  # Calendar and Date Handling
  table_calendar: ^3.0.9
  intl: ^0.18.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
